using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Xml.Linq;

namespace TranslateOnTheFly
{
    public partial class SettingsForm : Form
    {

        String srcName, dstName;        

        public SettingsForm()
        {
            //Get settings from doc
            try
            {
                this.srcName = "";
                this.dstName = "";
                InitializeComponent();
                loadSettingsToForm();
            }
            catch (Exception e)
            {
                Logger.log.Error("Unable to initiate settings window", e);
                MessageBox.Show("Exception occured. See log for more information");
                Application.Exit();
            }
        }

        #region callback methods generated by GUI builder

        private void buttSettingsSave_Click(object sender, EventArgs e)
        {
            try
            {
                //Get and set current values
                Settings.set.dst = cbdstLang.Text.ToString();
                Settings.set.src = cbsrcLang.Text.ToString();

                //Save to file
                Settings.SaveSettings();    
                Logger.log.Info("Save button clicked and information saved to XML file");
            }
            catch (Exception ee)
            {
                Logger.log.Error("Exception occured", ee);
            }
            finally
            {
                //Dispose window
                this.Dispose();
            }   
        }

        private void loadSettingsToForm()
        {
            //Populate list
            foreach (Language l in Settings.set.languages)
            {
                cbdstLang.Items.Add(l.name.ToString());
                cbsrcLang.Items.Add(l.name);
            }
           
            //Get and set def languages
            cbdstLang.SelectedIndex = cbdstLang.Items.IndexOf(Settings.set.dst.ToString());
            cbsrcLang.SelectedIndex = cbsrcLang.Items.IndexOf(Settings.set.src.ToString());

            Logger.log.Info("Information loaded to form");
        }

        private void buttSetCancel_Click_1(object sender, EventArgs e)
        {
            this.Dispose();
        }
        #endregion

        private void SettingsForm_Load(object sender, EventArgs e)
        {

        }
    }

}
